apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: favorite-beer-redis
spec:
  serviceName: "favorite-beer-redis"
  replicas: 1
  selector:
    matchLabels:
      app: favorite-beer-redis
  template:
    metadata:
      labels:
        app: favorite-beer-redis
    spec:
      containers:
      - name: favorite-beer-redis
        image: redaptregistry.azurecr.io/redis:3.2-alpine
        command: ["redis-server"]
        args: ["--appendonly", "yes"]
        ports:
        - containerPort: 6379
          name: redis
---
apiVersion: v1
kind: Service
metadata:
  name: favorite-beer-redis
spec:
  selector:
    app: favorite-beer-redis
  ports:
  - name: redis
    port: 6379
    protocol: TCP
    targetPort: 6379
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: favorite-beer
  labels:
    app: favorite-beer
spec:
  replicas: 2
  selector:
    matchLabels:
      app: favorite-beer
  template:
    metadata:
      labels:
        app: favorite-beer
    spec:
      containers:
      - name: favorite-beer
        image: redaptregistry.azurecr.io/favorite-beer:v1
        env:
        - name: REDIS_HOST
          value: "favorite-beer-redis"
        - name: REDIS_PORT
          value: "6379"
        - name: SERVICE_SETTINGS_PATH
          value: "servicesettings_alt.json"
        ports:
        - name: http
          containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: favorite-beer
spec:
  selector:
    app: favorite-beer
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 31650
  type: LoadBalancer